//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lad.org.entities2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Ingresoes = new HashSet<Ingreso>();
        }
    
        public int Codigo_Producto { get; set; }
        public string NombreProd { get; set; }
        public string Composicion { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public int Cantidad_Por_Unidad_gr_ { get; set; }
        public int Marca { get; set; }
        public int Categoria { get; set; }
        public int Presentacion { get; set; }
        public int Laboratorio { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingresoes { get; set; }
        public virtual Laboratorio Laboratorio1 { get; set; }
        public virtual Marca Marca1 { get; set; }
        public virtual Presentacion Presentacion1 { get; set; }
    }
}
